version: '2'
services:
    mercure:
        image: dunglas/mercure
        environment:
            - JWT_KEY=CHANGEME
            - DEMO=1
            - ALLOW_ANONYMOUS=1
            - HEARTBEAT_INTERVAL=30s
            - CORS_ALLOWED_ORIGINS=*
            - PUBLISH_ALLOWED_ORIGINS=*
            - ADDR=:3000
        ports:
            - "3000:3000"
